name: 'Build'

on: push

jobs:
  tsc:
    name: 'Compile Typescript'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NodeJS v18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
